image: alpine/latest
packages:
  - bash
  - openssh
  - curl
  - git
  - tmux
  - tmate

tasks:
  - setup: |
      apk add --no-cache openssh tmate bash curl
      echo "Starting tmate..."
      tmate -S /tmp/tmate.sock new-session -d
      sleep 5
      echo "SSH Link:"
      tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
      echo "Web URL:"
      tmate -S /tmp/tmate.sock display -p '#{tmate_web}'
      tail -f /dev/null
